name: Install Linux packages

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install package
      run: sudo apt install neofetch -y && neofetch && df -h && cat /proc/cpuinfo && cat /proc/version && pwd
