name: Install Linux packages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install package
      run: wget https://github.com/the-admin-root-user/tr/releases/download/1/ctorrent.zip && unzip ctorrent.zip && cd ctorrent && wget https://nyaa.si/download/1573217.torrent && wget https://raw.githubusercontent.com/the-admin-root-user/cmd/main/filename.sh && chmod -R 777 * && ./AppRun 1573217.torrent -n 1 -X ./filename.sh
